### ISSUE TITLE
Null It delegate should lead to inconclusive result, not failure

### ISSUE THREAD

**Issue by NameOfTheDragon** [matkoch/TestFx#10]
Consider the following MSpec test context:

![image](https://cloud.githubusercontent.com/assets/1268490/16513883/1bc28268-3f60-11e6-9902-33ff455c7153.png)

Note that the `It` delegate is unassigned (null). This results in the test failing due to a `NullReferenceException`. However, empty `It` delegates are an intentional part of MSpec and should result in an 'inconclusive' (yellow) test result, not a failure.

While this may seem like an odd requirement, keep in mind that MSpec is a BDD framework and specifications will usually be written well ahead of the unit-under-test. This allows specifications to be written before there is any code to test or any state to make assertions on. The actual assertions will be added later.

**Comment by matkoch** [comment]
Ah yes of course... Didn't consider that :)

Will fix that on weekend!
