### ISSUE TITLE
MSpec [Subject] attribute treats the Concern argument as a method identifier

### ISSUE THREAD

**Issue by NameOfTheDragon** [matkoch/TestFx#8]
While it is a nice feature, the string argument to an MSpec [Subject] attribute (the `Concern `parameter) isn't necessarily supposed to be the name of a method of the subject. I believe it is intended more to be descriptive text, as in (for example):

    `[Subject(typeof(BankAccount), "funds transfer")]`

TestFX appears to cause this parameter to be treated as a method name and it get's highlighted in red and flagged (by ReSharper, I think) as an error when it doesn't correspond to a method name:

![image](https://cloud.githubusercontent.com/assets/1268490/16513197/652aa8c8-3f5a-11e6-8d8c-43b52817a9ae.png)

I'm not sure what mechanism causes this behaviour, but it doesn't happen with MSpec. I don't know if this is right or wrong, but I think it is at least worth opening a discussion as to whether this is desirable as it seems to suggest a different intent than that used in MSpec.

**Comment by matkoch** [comment]
You're completely right. Some parts of the ReSharper plugin are not yet _framework-aware_.
