### ISSUE TITLE
TestFX.MSpec - test contexts should be detected based on the presence of an It delegate, not the [Subject] attribute

### ISSUE THREAD

**Issue by NameOfTheDragon** [matkoch/TestFx#9]
In MSpec, the presence of a `[Subject]` attribute is completely optional. Test contexts are identified by the presence of one or more `It` delegates.

In TestFX, if the Subject attribute is not present on a test context, then it is not correctly discovered as a test, even though an It delegate is present.

**Comment by NameOfTheDragon** [comment]
Yes, there's nothing special about MSpec contexts other than that they contain a member that is a delegate of type `It`. Unlike (for example) xUnit, where the `[Fact]` attribute is the key factor.

**Comment by matkoch** [comment]
In Mspec, isn't it the key factor to have a `Because` field? Otherwise also behaviors would be executed.

**Comment by NameOfTheDragon** [comment]
That's true, but behaviours without assertions are not really tests. I guess the 'acid test' is to try it:
![image](https://cloud.githubusercontent.com/assets/1268490/16540803/d59c8432-4068-11e6-93eb-1cafd311d1b4.png)
